### ISSUE TITLE
Incorrect information displayed in manage user page

### ISSUE THREAD

**Issue by madalincm** [mozilla/olympia#1020]
Steps to reproduce:
1. As an admin open the mange page of any user.

Expected results:
Everything is displayed correctly.

Actual results:
The username, display name and the email address are not correctly displayed. Also the user photo, location and other info are not correct or their fields are empty

Notes/Issues:
This issue is only reproducing in manage user page (as an admin), this is not reproducing in edit profile page. 
Verified in FF42 (Win7) Issue can be reproduced in addons.allizom.org and addons-dev.allizom.org
Screencast for this issue: http://screencast.com/t/rGPF8qNxLp

**Comment by andymckay** [comment]
This is the issue that @wagnerand fixed in #1023

**Comment by madalincm** [comment]
The issue is still reproducing in addons-dev.allizom.org
Please view this screencast: http://screencast.com/t/oGmdj2j6lp

**Comment by andymckay** [comment]
Fixed now, there was a problem with the deploy.
